# Global PepperPy Configuration

# Environment settings
environment:
  log_level: INFO
  debug: false
  timezone: UTC

# Default LLM settings
llm:
  default_provider: openai
  default_model: gpt-4-turbo-preview
  timeout: 30.0
  max_retries: 3
  retry_delay: 1.0

# Memory settings
memory:
  default_type: simple
  max_history: 100
  ttl: 3600  # 1 hour
  storage:
    type: in_memory
    max_size: 1000

# Data store settings
data_store:
  default_type: chroma
  embeddings:
    provider: openai
    model: text-embedding-3-small
  vector_db:
    path: data/vector_store
    distance_metric: cosine

# Tool settings
tools:
  default_timeout: 10.0
  max_concurrent: 5
  rate_limits:
    web_search: 10  # requests per minute
    api_calls: 60   # requests per minute

# Security settings
security:
  allowed_domains: ["*"]
  blocked_domains: []
  max_token_usage: 100000
  require_user_confirmation: false
  sensitive_fields:
    - api_key
    - password
    - credentials

# Caching settings
cache:
  enabled: true
  backend: redis
  ttl: 3600
  max_size: 1000000

# Monitoring settings
monitoring:
  enabled: true
  metrics:
    - token_usage
    - response_time
    - error_rate
  alert_thresholds:
    error_rate: 0.1
    response_time: 5.0

# Resource limits
limits:
  max_tokens_per_request: 4000
  max_concurrent_requests: 10
  max_request_size: 10485760  # 10MB

# Integration settings
integrations:
  autogen:
    enabled: true
    config_path: config/autogen.yaml
  langchain:
    enabled: true
    config_path: config/langchain.yaml
  crewai:
    enabled: true
    config_path: config/crewai.yaml
  semantic_kernel:
    enabled: true
    config_path: config/semantic_kernel.yaml

# Development settings
development:
  mock_llm_responses: false
  mock_tool_responses: false
  profile_code: false
  debug_prompts: false 