name: Template Provider
version: 0.1.0
description: Template provider for DOMAIN tasks
author: PepperPy Team
category: domain  # Use correct domain: llm, rag, tts, embeddings, etc.
provider_name: template
entry_point: provider.TemplateProvider
required_config_keys:
  - api_key

# Default configuration values (MUST exist)
default_config:
  base_url: https://api.example.com/v1
  model: default-model
  temperature: 0.7
  max_tokens: 1024

# Schema for configuration values
config_schema:
  api_key:
    description: API key for the service
    required: true
    env_var: TEMPLATE_API_KEY
    type: string
    secret: true
  base_url:
    description: API base URL
    required: false
    default: https://api.example.com/v1
    type: string
  model:
    description: Model to use
    required: false
    default: default-model
    type: string
  temperature:
    description: Sampling temperature between 0.0 (deterministic) and 2.0 (creative)
    required: false
    default: 0.7
    type: float
    min: 0.0
    max: 2.0
  max_tokens:
    description: Maximum tokens to generate in the response
    required: false
    default: 1024
    type: integer
    min: 1

# Documentation
documentation:
  usage: |
    Template provider for DOMAIN tasks.

    Requires an API key which can be specified:
    1. As a constructor parameter: api_key="your-api-key"
    2. As an environment variable: TEMPLATE_API_KEY or PEPPERPY_DOMAIN__TEMPLATE__API_KEY

    Example usage:
    ```python
    from pepperpy import create_provider

    provider = create_provider("domain", "template", api_key="your-api-key")

    response = await provider.domain_method("input data")
    print(response)
    ```
  parameters:
    api_key:
      description: API key for the service
      required: true
      env_var: TEMPLATE_API_KEY
    model:
      description: Model to use
      required: false
      default: default-model
    temperature:
      description: Sampling temperature between 0.0 (deterministic) and 2.0 (creative)
      required: false
      default: 0.7
    max_tokens:
      description: Maximum tokens to generate in the response
      required: false
      default: 1024

# Define compatibility with PepperPy versions
pepperpy_compatibility: '>=0.1.0' 