"""
Core package providing fundamental functionality for PepperPy.

This package contains the core modules that provide the foundation for building
autonomous AI applications with PepperPy.
"""

from .base import (
    Configurable,
    Factory,
    Manager,
    Observable,
    Observer,
    PepperComponent,
    Provider,
    Registry,
)
from .config.base import (
    ConfigManager,
    ConfigRegistry,
    ConfigSource,
    EnvVarConfigSource,
    YamlConfigSource,
    create_default_config_manager,
)
from .errors import (
    AuthenticationError,
    ComponentError,
    ConfigurationError,
    ConnectionError,
    DuplicateError,
    EventError,
    InitializationError,
    NotFoundError,
    PepperError,
    PermissionError,
    ProviderError,
    ResourceError,
    SecurityError,
    StateError,
    ValidationError,
    WorkflowError,
    error_handler,
)
from .events.base import (
    AsyncEventListener,
    EventBus,
    EventFilter,
    EventListener,
    EventSourceFilter,
    EventTypeFilter,
    create_event_bus,
)
from .observability.base import (
    Counter,
    Gauge,
    Histogram,
    Metric,
    MetricsCollector,
    ObservabilityManager,
    Span,
    Tracer,
    create_observability_manager,
)
from .protocols.base import (
    Configurable,
    Factory,
    Identifiable,
    Initializable,
    Manager,
    Observable,
    Observer,
    Provider,
    Serializable,
    Validatable,
)
from .registry.base import (
    Registry,
    RegistryFactory,
    RegistryManager,
    TypeRegistry,
    create_registry_manager,
)
from .security.base import (
    Permission,
    Principal,
    Role,
    SecurityContext,
    SecurityManager,
    User,
    create_security_manager,
)
from .types import (
    BaseComponent,
    ComponentID,
    ComponentT,
    ConfigDict,
    ConfigT,
    Event,
    EventData,
    EventT,
    Identifiable,
    Json,
    Metadata,
    MetadataDict,
    Priority,
    ProviderID,
    Result,
    Serializable,
    Status,
    Validatable,
    Versionable,
)

__all__ = [
    # Base
    "PepperComponent",
    "Registry",
    "Factory",
    "Manager",
    "Provider",
    "Configurable",
    "Observable",
    "Observer",
    # Config
    "ConfigSource",
    "EnvVarConfigSource",
    "YamlConfigSource",
    "ConfigManager",
    "ConfigRegistry",
    "create_default_config_manager",
    # Errors
    "PepperError",
    "ConfigurationError",
    "ValidationError",
    "ComponentError",
    "InitializationError",
    "StateError",
    "ProviderError",
    "ConnectionError",
    "AuthenticationError",
    "ResourceError",
    "NotFoundError",
    "DuplicateError",
    "SecurityError",
    "PermissionError",
    "EventError",
    "WorkflowError",
    "error_handler",
    # Events
    "EventListener",
    "AsyncEventListener",
    "EventFilter",
    "EventTypeFilter",
    "EventSourceFilter",
    "EventBus",
    "create_event_bus",
    # Protocols
    "Initializable",
    "Configurable",
    "Observable",
    "Observer",
    "Identifiable",
    "Validatable",
    "Serializable",
    "Factory",
    "Provider",
    "Manager",
    # Registry
    "Registry",
    "RegistryFactory",
    "TypeRegistry",
    "RegistryManager",
    "create_registry_manager",
    # Security
    "Permission",
    "Principal",
    "Role",
    "User",
    "SecurityContext",
    "SecurityManager",
    "create_security_manager",
    # Observability
    "Metric",
    "Counter",
    "Gauge",
    "Histogram",
    "Span",
    "Tracer",
    "MetricsCollector",
    "ObservabilityManager",
    "create_observability_manager",
    # Types
    "BaseComponent",
    "ComponentT",
    "ConfigT",
    "Event",
    "EventT",
    "Result",
    "Status",
    "Priority",
    "Metadata",
    "Serializable",
    "Validatable",
    "Identifiable",
    "Versionable",
    "Json",
    "ConfigDict",
    "MetadataDict",
    "EventData",
    "ComponentID",
    "ProviderID",
]
