"""Public API for HTTP module.

This module provides the public API for HTTP client and server.
"""

from pepperpy.http import (
    # Errors
    AuthenticationError,
    AuthorizationError,
    ClientError,
    ClientResponse,
    ConnectionError,
    # Server
    FunctionHandler,
    Handler,
    HandlerError,
    # Client
    HTTPClient,
    HTTPError,
    HTTPXClient,
    JSONHandler,
    MiddlewareError,
    RequestError,
    RequestOptions,
    ResponseError,
    Router,
    RoutingError,
    Server,
    ServerError,
    ServerOptions,
    TimeoutError,
    add_route,
    client_delete,
    client_get,
    client_head,
    client_options,
    client_patch,
    client_post,
    client_put,
    client_request,
    get_http_client,
    get_router,
    get_server,
    server_delete,
    server_get,
    server_head,
    server_options,
    server_patch,
    server_post,
    server_put,
    server_start,
    server_stop,
    set_http_client,
    set_server,
)

__all__ = [
    # Client
    "HTTPClient",
    "HTTPXClient",
    "RequestOptions",
    "ClientResponse",
    "client_delete",
    "client_get",
    "get_http_client",
    "client_head",
    "client_options",
    "client_patch",
    "client_post",
    "client_put",
    "client_request",
    "set_http_client",
    # Server
    "FunctionHandler",
    "Handler",
    "JSONHandler",
    "Router",
    "Server",
    "ServerOptions",
    "add_route",
    "server_delete",
    "server_get",
    "get_router",
    "get_server",
    "server_head",
    "server_options",
    "server_patch",
    "server_post",
    "server_put",
    "set_server",
    "server_start",
    "server_stop",
    # Errors
    "AuthenticationError",
    "AuthorizationError",
    "ClientError",
    "ConnectionError",
    "HTTPError",
    "HandlerError",
    "MiddlewareError",
    "RequestError",
    "ResponseError",
    "RoutingError",
    "ServerError",
    "TimeoutError",
]
