"""Public API for HTTP module.

This module provides the public API for HTTP client and server.
"""

from pepperpy.http import (
    # Errors
    AuthenticationError,
    AuthorizationError,
    ClientError,
    ClientResponse,
    ConnectionError,
    # Server
    FunctionHandler,
    Handler,
    HandlerError,
    # Client
    HTTPClient,
    HTTPError,
    HTTPXClient,
    JSONHandler,
    MiddlewareError,
    RequestError,
    RequestOptions,
    ResponseError,
    Router,
    RoutingError,
    Server,
    ServerError,
    ServerOptions,
    TimeoutError,
    # Client functions
    add_route,
    # Utils
    check_status_code,
    client_delete,
    client_get,
    client_head,
    client_options,
    client_patch,
    client_post,
    client_put,
    client_request,
    format_headers,
    get_content_type,
    get_http_client,
    get_router,
    get_server,
    is_json_content,
    parse_json,
    parse_query_params,
    server_delete,
    server_get,
    server_head,
    server_options,
    server_patch,
    server_post,
    server_put,
    server_start,
    server_stop,
    set_server,
)

# Connection pooling
from pepperpy.http.client import (
    HTTPClientContext,
    HTTPConnectionPool,
    HTTPPoolConfig,
    create_http_pool,
    get_http_pool,
    http_client,
    initialize_default_http_pool,
    release_http_client,
)

__all__ = [
    # Errors
    "AuthenticationError",
    "AuthorizationError",
    "ClientError",
    "ConnectionError",
    "HandlerError",
    "HTTPError",
    "MiddlewareError",
    "RequestError",
    "ResponseError",
    "RoutingError",
    "ServerError",
    "TimeoutError",
    # Client
    "ClientResponse",
    "HTTPClient",
    "HTTPXClient",
    "RequestOptions",
    # Server
    "FunctionHandler",
    "Handler",
    "JSONHandler",
    "Router",
    "Server",
    "ServerOptions",
    # Client functions
    "client_delete",
    "client_get",
    "client_head",
    "client_options",
    "client_patch",
    "client_post",
    "client_put",
    "client_request",
    "get_http_client",
    # Server functions
    "add_route",
    "get_router",
    "get_server",
    "server_delete",
    "server_get",
    "server_head",
    "server_options",
    "server_patch",
    "server_post",
    "server_put",
    "server_start",
    "server_stop",
    "set_server",
    # Utils
    "check_status_code",
    "format_headers",
    "get_content_type",
    "is_json_content",
    "parse_json",
    "parse_query_params",
    # Connection pooling
    "HTTPConnectionPool",
    "HTTPPoolConfig",
    "HTTPClientContext",
    "create_http_pool",
    "get_http_pool",
    "get_http_client",
    "release_http_client",
    "initialize_default_http_pool",
    "http_client",
]
