"""Infrastructure components for the PepperPy library.

This package contains all the infrastructure components used by the PepperPy library,
including caching, connection pooling, events, logging, metrics, resilience, security,
and storage.
"""

from pepperpy.infra.cache import (
    AsyncCacheManager,
    CacheManager,
)
from pepperpy.infra.connection import (
    ConnectionPool,
    ConnectionPoolConfig,
    ConnectionStats,
    PoolStatus,
    close_pools,
    get_pool,
    initialize_pools,
    pooled_resource,
    register_pool,
    release_connection,
    unregister_pool,
)
from pepperpy.infra.events import (
    Event,
    EventBus,
    EventDispatcher,
    EventListener,
    EventPriority,
    EventSubscription,
    on_event,
    publish_event,
    subscribe,
    unsubscribe,
)
from pepperpy.infra.logging import (
    LogLevel,
    configure_logging,
    get_logger,
    set_log_level,
)
from pepperpy.infra.metrics import (
    Counter,
    Gauge,
    MetricCategory,
    PerformanceMetric,
    PerformanceResult,
    PerformanceTracker,
    Timer,
    benchmark,
    get_memory_usage,
    get_system_info,
    measure_memory,
    measure_time,
    performance_tracker,
    report_custom_metric,
)
from pepperpy.infra.resilience import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitState,
    ProviderFallback,
    get_circuit_breaker,
    get_fallback,
    reset_all_circuit_breakers,
    reset_circuit_breaker,
    with_circuit_breaker,
    with_fallback,
)
from pepperpy.infra.security import (
    AuthType,
    Credential,
    IdentityStore,
    PermissionLevel,
    SecurityManager,
    create_security_manager,
)
from pepperpy.infra.storage import (
    FileStorageProvider,
    MemoryStorageProvider,
    StorageProvider,
    StorageProviderRegistry,
    StorageType,
    get_provider,
    get_registry,
    register_provider,
    unregister_provider,
)

__all__ = [
    # Logging
    "LogLevel",
    "configure_logging",
    "get_logger",
    "set_log_level",
    # Metrics
    "Counter",
    "Gauge",
    "MetricCategory",
    "PerformanceMetric",
    "PerformanceResult",
    "PerformanceTracker",
    "Timer",
    "benchmark",
    "get_memory_usage",
    "get_system_info",
    "measure_memory",
    "measure_time",
    "performance_tracker",
    "report_custom_metric",
    # Connection
    "PoolStatus",
    "ConnectionPoolConfig",
    "ConnectionPool",
    "ConnectionStats",
    "close_pools",
    "get_pool",
    "initialize_pools",
    "pooled_resource",
    "register_pool",
    "release_connection",
    "unregister_pool",
    # Resilience
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitState",
    "ProviderFallback",
    "get_circuit_breaker",
    "get_fallback",
    "reset_all_circuit_breakers",
    "reset_circuit_breaker",
    "with_circuit_breaker",
    "with_fallback",
    # Security
    "AuthType",
    "Credential",
    "IdentityStore",
    "PermissionLevel",
    "SecurityManager",
    "create_security_manager",
    # Storage
    "StorageType",
    "StorageProvider",
    "MemoryStorageProvider",
    "FileStorageProvider",
    "StorageProviderRegistry",
    "get_registry",
    "register_provider",
    "unregister_provider",
    "get_provider",
    # Events
    "Event",
    "EventBus",
    "EventDispatcher",
    "EventListener",
    "EventPriority",
    "EventSubscription",
    "on_event",
    "publish_event",
    "subscribe",
    "unsubscribe",
    # Cache
    "CacheManager",
    "AsyncCacheManager",
]
