"""Public interfaces for PepperPy Interfaces module.

This module provides a stable public interface for the interfaces functionality.
It exposes the core protocols and interfaces that are considered part
of the public API.
"""

from pepperpy.interfaces.core import (
    Adapter,
    AsyncAdapter,
    AsyncCache,
    AsyncClosable,
    AsyncConfigurable,
    AsyncConverter,
    AsyncFactory,
    AsyncFilter,
    AsyncHandler,
    AsyncInitializable,
    AsyncIterator,
    AsyncObserver,
    AsyncProcessor,
    AsyncProvider,
    AsyncRegistry,
    AsyncRepository,
    AsyncService,
    AsyncValidatable,
    AsyncValidator,
    Cache,
    Closable,
    Configurable,
    Converter,
    Describable,
    Factory,
    Filter,
    Handler,
    Identifiable,
    Initializable,
    Iterator,
    JSONSerializable,
    Metadata,
    Nameable,
    Observable,
    Observer,
    Processor,
    Provider,
    Registry,
    Repository,
    Resettable,
    Serializable,
    Service,
    Validatable,
    Validator,
    Versioned,
)

# Re-export everything
__all__ = [
    # Base protocols
    "Identifiable",
    "Describable",
    "Nameable",
    "Versioned",
    "Metadata",
    "Serializable",
    "JSONSerializable",
    "Resettable",
    # Resource management
    "Closable",
    "AsyncClosable",
    "Initializable",
    "AsyncInitializable",
    "Configurable",
    "AsyncConfigurable",
    "Validatable",
    "AsyncValidatable",
    # Design pattern protocols
    "Observable",
    "Observer",
    "AsyncObserver",
    "Provider",
    "AsyncProvider",
    "Factory",
    "AsyncFactory",
    "Adapter",
    "AsyncAdapter",
    "Converter",
    "AsyncConverter",
    "Processor",
    "AsyncProcessor",
    "Handler",
    "AsyncHandler",
    "Iterator",
    "AsyncIterator",
    "Filter",
    "AsyncFilter",
    "Validator",
    "AsyncValidator",
    # Data management
    "Cache",
    "AsyncCache",
    "Registry",
    "AsyncRegistry",
    "Repository",
    "AsyncRepository",
    # Service management
    "Service",
    "AsyncService",
]
