name: domain/template
version: 0.1.0
description: Template provider for domain tasks
author: PepperPy Team

# Plugin classification
plugin_type: domain
category: domain_category
provider_name: template
entry_point: provider.TemplateProvider

# Configuration schema (JSON Schema format)
config_schema:
  type: object
  properties:
    api_key:
      type: string
      description: API key for external service
    model:
      type: string
      description: Model to use for processing
      default: default-model
    temperature:
      type: number
      description: Temperature parameter for generation
      default: 0.7
    max_tokens:
      type: integer
      description: Maximum tokens to generate
      default: 1000

# Default configuration
default_config:
  model: default-model
  temperature: 0.7
  max_tokens: 1000

# Example usage for testing
examples:
  - name: basic_example
    description: Basic usage example
    input:
      task: task_one
      param: test_value
    expected_output:
      status: success
      result: "Processed: test_value"
  
  - name: advanced_example
    description: Advanced usage with custom configuration
    input:
      task: task_two
      param: custom_parameter
      config:
        model: custom-model
    expected_output:
      status: success
      result: "Task two result: custom_parameter"

# Documentation
documentation:
  usage: |
    Template provider for domain tasks.
    
    Example usage:
    
    ```python
    from pepperpy import PepperPy
    
    app = PepperPy.create().with_domain("template").build()
    
    result = await app.domain.execute({
        "task": "task_one",
        "param": "my_value"
    })
    
    print(result)
    ``` 