# Basic metadata
name: {{plugin_path}}
version: 0.1.0
description: {{description}}
author: {{author}}

# Plugin categorization
plugin_type: {{domain}}
category: {{category}}
provider_name: {{provider}}
entry_point: provider.{{provider_class}}

# Version constraints
min_framework_version: 0.1.0
# max_framework_version: 0.2.0  # Uncomment and set when needed

# Configuration schema (JSON Schema format)
config_schema:
  type: object
  properties:
    # Define your configuration properties here
    example_option:
      type: string
      description: Example configuration option
      default: default_value
    timeout:
      type: integer
      description: Operation timeout in seconds
      default: 30
      minimum: 1
      maximum: 300
  # Uncomment to specify required properties
  # required:
  #   - example_required_option

# Default configuration values
default_config:
  example_option: default_value
  timeout: 30

# Examples for testing
examples:
  - name: basic_example
    description: Basic example of plugin functionality
    input:
      task: example_task
      parameter: example_value
    expected_output:
      status: success
      result: example_result

  - name: error_example
    description: Example of error handling
    input:
      task: invalid_task
    expected_output:
      status: error
      message: Invalid task specified 