name: Validate Cursor Rules

on:
  push:
    branches: [main]
    paths:
      - '.cursor/rules/**'
      - 'scripts/rules-updater.py'
      - '.github/workflows/rules-validation.yml'
  pull_request:
    branches: [main]
    paths:
      - '.cursor/rules/**'
      - 'scripts/rules-updater.py'
      - '.github/workflows/rules-validation.yml'

jobs:
  validate-rules:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Validate rules
        run: python scripts/rules-updater.py validate
      
      - name: Run scanner (for reference)
        run: python scripts/rules-updater.py scan
        continue-on-error: true 